# Generated by Django 4.1.6 on 2023-05-10 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_login_user_phone_user_userlastname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='login',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='userlastname',
            new_name='name',
        ),
    ]
