# Generated by Django 4.2 on 2023-05-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_prod', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=20)),
                ('images', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
            ],
            options={
                'db_table': 'main',
            },
        ),
    ]
