# Generated by Django 4.2 on 2023-05-05 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='main',
            old_name='images',
            new_name='price',
        ),
    ]
